version: '3.4'

services:
  persondetailsapi:
    image: persondetails
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=PersonDb;User Id=docker-user;Password=Password123;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False;Application Intent=ReadWrite;Multi Subnet Failover=False;
      - ConnectionStrings__MongoDb=mongodb://mongo:27017
    depends_on:
      - sqlserver
      - mongo
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - mynetwork

  mongo:
    image: mongo:latest
    container_name: mongodb-container
    command: mongod --auth --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_DATABASE: PersonDb
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Test123!
    networks:
      - mynetwork

volumes:
  mongodb-data:

networks:
  mynetwork:
